name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CACHE_NAME: ${{ github.repository_owner }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: ${{ env.CACHE_NAME }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build & cache
      run: |
        nix build --json \
          | jq -r '.[].outputs | to_entries[].value' \
          | cachix push "$CACHE_NAME"
